---
- name: Fetch user/group list from gitlab
  hosts: localhost
  become: false

  vars:
    repo_scheme: 'http'
    partial_repo_url: ""
    gitlab_access_token_name: ""
    gitlab_access_token: ""
    repo_version: master

  tasks:
    - block:
      - name: Generate gitlab repo
        set_fact:
          repo_url: "{{ repo_scheme }}://{{ gitlab_access_token_name }}:{{ gitlab_access_token }}@{{partial_repo_url}}"
      - name: Remove folder 'files/'
        file:
          path: "files"
          state: absent
      - name: Fetch configuration
        git:
          repo: "{{ repo_url }}"
          dest: "files"
          version: "{{ repo_version }}"

- name: Overwrite httpd.conf file
  hosts: all
  tasks:
    - block:
      - name: Create /home/httpd directory 
        file:
          path: /home/httpd/rhel_6
          state: directory
          mode: '0755'

      - name: Copy httpd.conf file in /home/httpd/rhel_6
        copy:
          remote_src: yes
          src: /etc/httpd/conf/httpd.conf
          dest: /home/httpd/rhel_6
        
      - name: Copy httpd.conf file 
        copy:
          src: files/rhel6/httpd.conf
          dest: /etc/httpd/conf/httpd.conf
      when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "6"
      
    - block:
      - name: Create /home/httpd directory 
        file:
          path: /home/httpd/rhel_7
          state: directory
          mode: '0755'

      - name: Copy httpd.conf file in /home/httpd/rhel_7
        copy:
          remote_src: yes
          src: /etc/httpd/conf/httpd.conf
          dest: /home/httpd/rhel_7

      - name: Copy httpd.conf file 
        copy:
          src: files/rhel7/httpd.conf
          dest: /etc/httpd/conf/httpd.conf
          owner: root
          group: root
          force: yes
      when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "7"
    
    - block:
      - name: Create /home/httpd directory 
        file:
          path: /home/httpd/rhel_8
          state: directory
          mode: '0755'
      - name: Copy httpd.conf file in /home/httpd/rhel_8
        copy:
          remote_src: yes
          src: /etc/httpd/conf/httpd.conf
          dest: /home/httpd/rhel_8
      - name: Copy httpd.conf file 
        copy:
          src: files/rhel8/httpd.conf
          dest: /etc/httpd/conf/httpd.conf
          owner: root
          group: root
          force: yes
      when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "8"

    - name: reload httpd service
      service:
        name: httpd
        state: restarted
        enabled: yes
