---
- name: Fetch user/group list from gitlab
  hosts: localhost
  become: false

  vars:
    repo_scheme: 'http'
    partial_repo_url: ""
    gitlab_access_token_name: ""
    gitlab_access_token: ""
    repo_version: master

  tasks:
    - block:
      - name: Generate gitlab repo
        set_fact:
          repo_url: "{{ repo_scheme }}://{{ gitlab_access_token_name }}:{{ gitlab_access_token }}@{{partial_repo_url}}"
      - name: Remove folder 'files/'
        file:
          path: "files"
          state: absent
      - name: Fetch configuration
        git:
          repo: "{{ repo_url }}"
          dest: "files"
          version: "{{ repo_version }}"

- name: Overwrite /etc/pam.d/password-auth file
  hosts: all
  tasks:
    - name: Copy password-auth file 
      copy:
        src: files/rhel6/password-auth
        dest: /etc/pam.d/password-auth
        owner: root
        group: root
        force: yes
      when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "6"

    - name: Copy password-auth file 
      copy:
        src: files/rhel7/password-auth
        dest: /etc/pam.d/password-auth
        owner: root
        group: root
        force: yes
      when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "7"

    - name: Copy password-auth file 
      copy:
        src: files/rhel8/password-auth
        dest: /etc/pam.d/password-auth
        owner: root
        group: root
        force: yes
      when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "8"


