---
- name: Generate new password for 'Ansible' Credential
  hosts: localhost

  tasks:
    - name: Generate new password and store in variable
      set_fact:
        new_password: "{{ lookup('password', '/dev/null length=10 chars=ascii_leters,digits') }}"

    # - debug:
    #     msg: "new_password={{ new_password }}"

- name: Modify 'Ansible' account password with timuser
  hosts: all
  gather_facts: false

  tasks:
    - name: Modify 'Ansible' account password
      raw: echo '{{ hostvars["localhost"]["new_password"] }}' | sudo -H LANG=C passwd ansible --stdin

- name: Update password of 'ansible' credential in Tower
  hosts: localhost

  vars:
      tower_host: 'https://10.95.26.30'
      credential_id: 10
      endpoint: '{{ tower_host }}/api/v2/credentials/{{ credential_id}}/'
      tower_token: ''

  tasks:
    - name: Get credential first.
      uri:
        url: "{{ endpoint }}"
        method: GET
        status_code: 200
        headers:
          Authorization: "Bearer {{ tower_token }}"
        validate_certs: false
      register: this

    # - debug:
    #     var: this.json

    - set_fact:
        credential_content:
          name: "{{ this.json.name }}"
          description: "{{ this.json.description }}"
          organization: "{{ this.json.organization }}"
          credential_type: "{{ this.json.credential_type }}"
          inputs:
            password: '{{ hostvars["localhost"]["new_password"] }}'
            username: '{{ this.json.inputs.username }}'
            become_method: 'sudo'
            become_password: '{{ hostvars["localhost"]["new_password"] }}'
    # - debug:
    #    msg: "{{ credential_content | to_json }}"

    - name: Update password of 'ansible' credential in Tower
      uri:
        url: "{{ endpoint }}"
        method: PATCH
        body: '{{ credential_content | to_json }}'
        body_format: json
        status_code: 200
        headers:
          Authorization: "Bearer {{ tower_token }}"
        validate_certs: false
