---
- name: copy file to remote
  copy:
    src: "files/{{ item }}"
    dest: "/tmp/tempfile"
    force: yes

- name: get checksum
  stat:
    path: "/tmp/tempfile"
    checksum_algorithm: sha256
  register: fileA

- name: get checksum
  stat:
    path: "{{ item }}"
    checksum_algorithm: sha256
  register: fileB

# - name: show
#   debug:
#     msg: "{{ fileA.stat.checksum }}"

# - name: show
#   debug:
#     msg: "{{ fileB.stat.checksum }}"
#   when: " 'checksum' in fileB.stat "

- name: Set checksum
  set_fact:
    checksum: ""
  when: " 'checksum' not in fileB.stat "

- name: Set checksum
  set_fact:
    checksum: "{{ fileB.stat.checksum }}"
  when: " 'checksum' in fileB.stat "

- name: compare result
  set_fact:
    output: "{{ output }}\n[OK] {{ item }} is matched."
  when: fileA.stat.checksum == checksum

- name: compare result
  set_fact:
    output: "{{ output }}\n[FAIL] {{ item }} is not MATCHED."
  when: fileA.stat.checksum != checksum