---
###
- name: Section 2-5 User password style policy check - pre_task
  set_fact:
    section2_5_result: false
    section2_6_result: false

- name: Section 2-5 User password style policy check in RHEL6
  include_tasks: section_2_5_rhel6.yml
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "6"
    
- name: Section 2-5 User password style policy check in RHEL7
  include_tasks: section_2_5_rhel7.yml
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "7"

- name: Section 2-5 User password style policy check in RHEL8
  include_tasks: section_2_5_rhel7.yml
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "8"
